spring.application.name=demojpa
spring.datasource.url=${NEON_DATABASE_URL}
spring.datasource.username=${NEON_DATABASE_USERNAME}
spring.datasource.password=${NEON_DATABASE_PASSWORD}
# Numero maximo de conexiones en el pool
spring.datasource.hikari.maximum-pool-size=2
# Tiempo maximo para obtener una conexion del pool
spring.datasource.hikari.connection-timeout=30000
server.port=8081
